<a href="https://colab.research.google.com/github/JOWIN-JOSEPH-RAJU/AI-Data_Science-Lab/blob/main/Exp_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# VAIVA QUESTIONS

---


1.   What is KNN?
2.   what is Irish Dataset ? which are the features and class labels?
3.   From sklearn dataset import load_iris. what is the use of this
4. X=iris.data() what is the data attribute it contains
5. y=iris.target what does the target attribute do ?
6. what is  model training and model evaluation
7. why do we split the data into trainning and test dat set
8. which is an ideal training and test dataset
9. how do we split the dataset into training and testing data set. Explain train test split ?
10. prediction we made on which type of data?how do you made prediction ?what is KNN predict
11. what is scikit learn?
12. how do you create and train the KNN classifier .what does kneighbour classifier (n_neighbours = 3) mean
13. what is accuracy of a model ? how do you find the accuracy of KNN classifier created ?what is accuracy score?
14. HOW DO YOU PRINT BOTH CORRECT & WRONG PREDITION & EXPLAIN THE CODE



# What is KNN?

---


*  The K-Nearest Neighbors (KNN) algorithm is a simple, supervised machine learning algorithm that can be used for both classification and regression tasks. It works by finding the K most similar training examples to a new data point and then predicting the label of the new data point based on the labels of the K nearest neighbors.

* Advantages of KNN

   * KNN is a simple and easy-to-understand algorithm.
   * KNN is very flexible and can be used for both classification and regression tasks.
   * KNN is relatively non-parametric, which means that it does not make any assumptions about the underlying distribution of the data.
   * KNN is very adaptable and can learn from new data as it becomes available.

* Disadvantages of KNN

   * KNN can be computationally expensive, especially for large datasets.
  *  KNN is sensitive to the choice of the K parameter. If K is too small, the algorithm can be overfitting and will not generalize well to new data. If K is too large, the algorithm can be underfitting and will not be able to learn the patterns in the data.
   * KNN can be sensitive to the choice of distance metric. Different distance metrics can produce different results, so it is important to choose a distance metric that is appropriate for the data.



# what is Irish Dataset ? which are the features and class labels?

---
* The Iris Dataset is a classic machine learning dataset that consists of 150 samples of 3 species of Iris flowers (Iris setosa, Iris virginica, and Iris versicolor). Each sample has 4 features: sepal length, sepal width, petal length, and petal width. The dataset is often used to test machine learning algorithms, such as classification and regression algorithms.

* Features:

    * Sepal length (cm)
    * Sepal width (cm)
    * Petal length (cm)
    * Petal width (cm)
* Class labels:

    * Iris setosa (0)
    * Iris virginica (1)
    * Iris versicolor (2)


# From sklearn dataset import load_iris. what is the use of this

---
* The **sklearn.datasets.load_iris() **function is used to load the Iris dataset into a Python program
* The load_iris() function returns a dictionary-like object that contains the following attributes:

    * data: A NumPy array containing the feature values for each sample.
    * target: A NumPy array containing the class labels for each sample.
    * target_names: A list of the class names.
    * feature_names: A list of the feature names.
    * DESCR: A full description of the dataset.


In [9]:
from sklearn.datasets import load_iris

iris = load_iris()

print(iris.data)
print(iris.target)
print(iris.target_names)
print(iris.feature_names)
print(iris.DESCR)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# X=iris.data() what is the data attribute it contains

---
The iris.data() attribute contains a NumPy array containing the feature values for each sample in the Iris dataset. Each row in the array represents a sample, and each column represents a feature. The Iris dataset has 4 features: sepal length, sepal width, petal length, and petal width.


In [17]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data

# Print the first 5 rows of the feature array
print(X[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


# y=iris.target what does the target attribute do ?

---
he iris.target attribute contains a NumPy array containing the class labels for each sample in the Iris dataset. Each element in the array represents the class label for a sample. The Iris dataset has 3 classes: Iris setosa, Iris virginica, and Iris versicolor.


In [24]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
y=iris.target
print(y[100:150])

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


# what is model trainning and model evaluation

---
* Model training is the process of teaching a machine learning model to perform a specific task. This is done by feeding the model a set of training data, which consists of input data and the corresponding output data. The model learns to predict the output data for new input data by finding patterns in the training data.
* Model evaluation is the process of assessing the performance of a trained machine learning model on a held-out test set. The test set is a set of data that the model was not trained on. By evaluating the model on the test set, we can get an unbiased estimate of how well the model will perform on new data.

1.Collect a dataset of training data.
2.Split the dataset into a training set and a test set.
3.Choose a machine learning algorithm
4.Train the model on the training set
5.Evaluate the model on the test set

# why do we split the data into trainning and test dat set

---
We split the data into training and test datasets for two main reasons:


    1. To avoid overfitting. Overfitting occurs when a machine learning model learns the training data too well and is unable to generalize to new data. By splitting the data into training and test datasets, we can train the model on the training set and evaluate its performance on the test set. If the model performs poorly on the test set, then we know that it is overfitting the training data and we need to take steps to address this, such as collecting more training data or using a different model architecture.
    2. To get an unbiased estimate of the model's performance. If we evaluate the model on the same data that it was trained on, then we are likely to get an overly optimistic estimate of its performance.



# how do we split the dataset into training and testing data set.

---

* To split the dataset into training and testing datasets, we can use the train_test_split() function from the scikit-learn library in Python.

* The train_test_split() function takes the following arguments:

    * X: The input data.
    * y: The output data.
    * test_size: The proportion of the data to be used for the test set. The default value is 0.25.
    * random_state: An integer seed used to shuffle the data before splitting it. This ensures that the split is reproducible.

* The function returns four NumPy arrays:

    * X_train: The training input data.
    * X_test: The test input data.
    * y_train: The training output data.
    * y_test: The test output data.



In [25]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
Y=iris.target



# Split the data into training and test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Explain train test split ?

---

* Train-test split is a technique used to evaluate the performance of machine learning models. It involves splitting the dataset into two subsets: a training set and a test set. The training set is used to train the model, and the test set is used to evaluate the model's performance on unseen data.


    *  Split the dataset into two subsets: the training set and the test set. The training set is typically larger than the test set, as it is used to train the model. The test set should be large enough to provide a reliable estimate of the model's performance on unseen data.
    *  Train the model on the training set. The model is trained by feeding it the training data and allowing it to learn the patterns in the data.
    *  Evaluate the model on the test set. The model's performance is evaluated by feeding it the test data and predicting the output labels. The predictions are then compared to the actual labels to assess the model's accuracy.


# prediction we made on which type of data?how do you made prediction ?what is KNN predict

---
1.We can make predictions on any type of data that can be represented as a numerical vector. For example, we can make predictions on data that represents images, text, or audio.

2.To make predictions using KNN, we first need to train a KNN model. This involves feeding the model a set of training data, which consists of input data and the corresponding output labels. The model learns to predict the output labels for new input data by finding the K most similar training examples and averaging the output labels for those examples.


In [28]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

# Load the training data


# Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)

# Train the model
knn.fit(X_train, y_train)

# Make predictions on new data
X_new = np.array([[7,5 ]])
y_pred = knn.predict(X_new)

# Print the predictions
print(y_pred)


[0]


# what is scikit learn?

---
Scikit-learn is a free software machine learning library for the Python programming language. It features various classification, regression and clustering algorithms including support-vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy.



# how do you create and train the KNN classifier .what does kneighbour classifier (n_neighbours = 3) mean

---
* To create and train a KNN classifier in Python, we can use the KNeighborsClassifier class from the scikit-learn library.

* import numpy as np
from sklearn.neighbors import KNeighborsClassifier

Load the training data
X_train = np.array([[1, 2], [3, 4], [5, 6]])
y_train = np.array([0, 1, 2])

Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)

Train the model
knn.fit(X_train, y_train)

# what is accuracy of a model ? how do you find the accuracy of KNN classifier created ?what is accuracy score?

---
* Accuracy is a measure of how well a machine learning model performs on a test set. It is calculated as the percentage of correct predictions that the model makes on the test set.


KNN ALGORITH
AIM :IMPLEMENT K NEAREST NEIGHBOUR ALGOURITHM TO CLASSIFY ANY DATA SET PRINT BOTH CORRECT AND WRONG PREDICTIONS ML LIBRARY CLASS CAN BE USED FOR THIS PROBLEM ASSUME K = 3



---



#PROGRAM

---



In [33]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


iris=load_iris()
X=iris.data
Y=iris.target
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred=knn.predict(X_test)
print("accuracy of the model :",knn.score(X_test,y_test )*100,"%\n")
print("ACTUAL \t\t PREDICTED \t PREDICTION")
for i in range (len(X_test)):
  if y_pred[i]==y_test[i]:
    print(iris.target_names[y_test[i]]," \t",iris.target_names[y_pred[i]],"\t","Correct")
  else:
    print(iris.target_names[y_test[i]],"\t",iris.target_names[y_pred[i]],"\t","Incorrect")





accuracy of the model : 100.0 %

ACTUAL 		 PREDICTED 	 PREDICTION
versicolor  	 versicolor 	 Correct
setosa  	 setosa 	 Correct
virginica  	 virginica 	 Correct
versicolor  	 versicolor 	 Correct
versicolor  	 versicolor 	 Correct
setosa  	 setosa 	 Correct
versicolor  	 versicolor 	 Correct
virginica  	 virginica 	 Correct
versicolor  	 versicolor 	 Correct
versicolor  	 versicolor 	 Correct
virginica  	 virginica 	 Correct
setosa  	 setosa 	 Correct
setosa  	 setosa 	 Correct
setosa  	 setosa 	 Correct
setosa  	 setosa 	 Correct
versicolor  	 versicolor 	 Correct
virginica  	 virginica 	 Correct
versicolor  	 versicolor 	 Correct
versicolor  	 versicolor 	 Correct
virginica  	 virginica 	 Correct
setosa  	 setosa 	 Correct
virginica  	 virginica 	 Correct
setosa  	 setosa 	 Correct
virginica  	 virginica 	 Correct
virginica  	 virginica 	 Correct
virginica  	 virginica 	 Correct
virginica  	 virginica 	 Correct
virginica  	 virginica 	 Correct
setosa  	 setosa 	 Correct
setosa  	 set